- README.md
- src/index.ts
- test/fixtures/lang/en.json
- test/plurization.test.ts
- test/translate.test.ts
will watch any changes happens to the activeMessages object and then return the correct translation
the new wTrans and wTransChoice returns a Ref<T> `ComputedRef<T>` which enables vue to watch and recalculate any changes that happens to the translation.
so any changes to the current language or the files loading took more time it will always return the newest version of the translation.
> add new wTrans and wTransChoice

- README.md
- src/index.ts
- src/interfaces/options.ts
- test/setup.ts
- test/translate.test.ts
This PR adds the capability to use the `fallbackLang` option.
If the `lang` was not provided or it does not exist, it will try to get from the `fallbackLang` option.
If the `fallbackLang` was not provided the default is: `en`.
Closes #36
> feat: Add `fallbackLang` option

- src/loader.ts
- test/fixtures/lang/en/domain/car.php
- test/fixtures/lang/en/domain/user.php
- test/loader.test.ts
This PR adds support for subdirectories in a language folder like:` lang/en/domain/car.php`.
Solves #43 .
> Support for subdirectories in a language

- src/utils/has-php-translations.ts
👋
This PR reapplies the fix from #50 that was overwritten in a84e457.
> Reapply fix for VITE_LARAVEL_VUE_I18N_HAS_PHP error

- README.md
A small comma in README.md that killed an hour of my time.
> Missed comma in translation for vue template

- README.md
- src/index.ts
- src/interfaces/plugin-options.ts
- test/class.test.ts
This PR is a follow-up to https://github.com/xiCO2k/laravel-vue-i18n/issues/56 and refactors the library to use a class-based approach. **There are no breaking changes** - existing usages should continue to work just fine. Tests have been provided.
The goal is to allow creating multiple translator instances, which allows translating different parts of the UI in different languages. This is useful in certain scenarios, such as for a translation tool, or some app that displays a preview of some document or component in a different language than the rest of the UI.
All language loading and translation logic remains the same - it has merely been moved inside the `I18n` class. It is possible to create multiple instances of this class, each with different options (language, resolver). These …
> Refactor to class instance, allowing multiple instances

- src/index.ts
- test/fixtures/lang/de.json
- test/translate.test.ts
I've added a simple and easy way to use language arrays, without bloating the .json files.
Closes #71
> feat: add support for language arrays

- src/index.ts
- src/loader.ts
- test/fixtures/lang/en/nested/cars/car.php
- test/fixtures/lang/pt/nested/cars/car.php
- test/loader.test.ts
- test/translate.test.ts
Fixes #84
Also adds `/` as a possible trans delimiter. The reason is type hinting in PHPStorm because that's the default way Laravel has made nested translations.
> fix: Nested translations aren't translated

- src/index.ts
- test/fixtures/lang/en.json
- test/fixtures/lang/pt.json
- test/translate.test.ts
When using the `/` delimiter we should check whether the translation exists or not before replacing the string.
> fix: Translation of strings that use delimiter symbols

- src/index.ts
- src/interfaces/options.ts
- test/class.test.ts
- test/fixtures/lang/en.json
- test/setup.ts
- test/translate.test.ts
Fix for [Issue 87: FallbackLocale not working](https://github.com/xiCO2k/laravel-vue-i18n/issues/87)
fallback locale is loaded first (in browser mode)
if active message has no value or the value equals with the key then use fallback locale translation
> Fix fallback locale

- src/index.ts
- src/mix.ts
- test/fixtures/lang/pt.json
- test/translate.test.ts
> fix: Translations with `/` no need to replace with `.`.

- package.json
- src/index.ts
> fix: mixin typings

- package-lock.json
- package.json
- src/vite.ts
TypeScript throws an error when I try to use Vite config file in TS format:
This PR add correct typings to the Vite plugin.
> fix: Vite plugin typings

- README.md
- package-lock.json
- src/interfaces/plugin-options.ts
- src/loader.ts
- src/vite.ts
- test/fixtures/locales/en/auth.php
- test/fixtures/locales/en/domain/user.php
- test/loader.test.ts
With this PR, we can now pass additional paths from where we will load our translations, this is usefull when we are splitting our application's translations into different folders/paths, and/or we are using a package that helps us override default translations.
> Vite plugin options

- src/index.ts
- test/plurization.test.ts
- test/translate.test.ts
> fix: Translations set to null if key doesn't exist

- src/index.ts
- test/fixtures/lang/pt.json
- test/translate.test.ts
> fix: Not handling empty string translations.

- src/index.ts
- test/translate.test.ts
> fix: Issue when calling the loadLanguageAsync in parallel.

- src/loader.ts
- test/fixtures/lang/en/ignore.php
- test/loader.test.ts
> fix: Ignore `null` and empty `array` `php` translations

- src/index.ts
> fix: Check for `null` on `makeReplacements

- src/vite.ts
For a while now, I haven't understood why the Vite dev script stopped with an error message indicating an attempt to delete an already deleted language file when called buildEnd function.
```
node:fs:1876
binding.unlink(path);
^
Error: ENOENT: no such file or directory, unlink 'lang/php_en.json'
at unlinkSync (node:fs:1876:11)
at file:///github/secret/node_modules/.pnpm/laravel-vue-i18n@2.7.6_typescript@5.3.3/node_modules/laravel-vue-i18n/dist/vite.mjs:12:33
at Array.forEach (<anonymous>)
at process.clean (file:///github/secret/node_modules/.pnpm/laravel-vue-i18n@2.7.6_typescript@5.3.3/node_modules/laravel-vue-i18n/dist/vite.mjs:12:15)
at process.emit (node:events:531:35)
at process.exit (node:internal/process/per_thread:192:15)
at process.<anonymous> …
```
> fix: check file existence before unlinking (vite.buildEnd --> clear)

- README.md
This adds this so far undocumented part introduced in #103 into the docs.
> docs: fallbackMissingTranslations

- src/loader.ts
- test/fixtures/lang/vendor/package-example/en/messages.php
- test/fixtures/lang/vendor/package-example/pt/messages.php
- test/folderIsolationUtil.ts
- test/loader.test.ts
This update addresses an issue where a 'php_vendor.json' file is generated but not utilized, as it is not imported by the plugin resolver.
**Changes**
- Removed the generation of the 'php_vendor.json' file from the published package language files.
- Merged the content of 'php_vendor.json' directly into the actual language files used by the resolver.
> Support for published package language vendor files

- src/loader.ts
- test/fixtures/lang/en/classnames.php
- test/fixtures/lang/en/enums.php
- test/loader.test.ts
> fix: Add `Enum`  and `class-name` support

- src/index.ts
Hi, @xiCO2k, thanks for developing a great package!
As already pulled in other packages, e.g. https://github.com/primefaces/primevue/issues/6199, https://github.com/inertiajs/inertia/pull/2099, it seems that the augmentations with custom properties should use the `'vue'` module instead of `'@vue/runtime-core'`. Also, it is documented [on the Vue.js page](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties).
For me it caused an issue with my Inertia app dev experience, where my `$page` property had lost its type in Vue SFC template. It seems it has been resolved with this commit (at least for me).
Cheers!
> Augment `vue` instead of `@vue/runtime-core`

- src/index.ts
- test/translate.test.ts
Add reactive current locale - Related to this #192
> Reactive Current Locale
